test_stage:
  pruning_modifiers:
    ConstantPruningModifier:
      targets: ['re:.*q_proj.weight', 're:.*k_proj.weight', 're:.*v_proj.weight',
      're:.*o_proj.weight', 're:.*gate_proj.weight', 're:.*up_proj.weight',
      're:.*down_proj.weight']
      start: 0
    OutputDistillationModifier:
      # targets: ['re:model.layers.\\d+$']
      targets: ["model.layers.0"]
      comparison: "square_head"
      start: 0
      orig_scale: 1.0
      distill_scale: 1.0
